# Generated by Django 3.0.6 on 2020-05-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
