# Generated by Django 3.0.6 on 2020-05-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20200519_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='date_created',
            field=models.DateTimeField(null=True),
        ),
    ]
